#启动端口号
server:
  port: 8099
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authority_managerment?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 960422
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      maxActive: 20
  jpa:
    open-in-view: false
#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#日志配置
logging:
  config: classpath:logback-spring.xml
